[phases.setup]
nixPkgs = ["go_1_21"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -tags netgo -ldflags '-w' -o api main.go"]

[start]
cmd = "./api"

[variables]
GOPROXY = "https://proxy.golang.org,direct"
GOSUMDB = "sum.golang.org"
